version: "3.8"

services:
  app:
    image: app-local-image
    container_name: app-local-container
    build:
      context: ./
      dockerfile: Dockerfile.local
      args:
        - PORT=${PORT}
        - MODE=local
    ports:
      - 8080:${PORT} # host:container
    volumes:
      - ./:/app
      - exclude:/app/node_modules/

volumes:
  exclude:
