version: "3.8"
services:
  app:
    container_name: app-container
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        - PORT=${PORT}
        - MODE=${MODE}
    ports:
      - 8080:${PORT} # host:container

    volumes:
      - ./:/app
      - exclude:/app/node_modules/

volumes:
  exclude:
