version: "3.8"
services:
  app:
    container_name: app-local-container
    image: app-local-image
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.local
      args:
        - PORT=${PORT}
        - MODE=start
    ports:
      - 8080:${PORT} # host:container

    volumes:
      - ./:/app
      - exclude:/app/node_modules/

volumes:
  exclude:
