FROM node:18-bullseye as build
RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm run build

FROM node:18-bullseye as deploy
RUN npm install -g pnpm

ARG PORT
ENV PORT=$PORT

WORKDIR /usr/src/app

COPY package*.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install --only=prod

COPY .env .
COPY --from=build /usr/src/app/dist ./dist

EXPOSE $PORT

CMD ["node", "dist/main"]
