FROM node:18-bullseye-slim
RUN npm install -g pnpm

# Create app directory
WORKDIR /app

ARG PORT
ENV PORT=$PORT
ARG MODE
ENV MODE=$MODE

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Bundle app source
COPY . .

EXPOSE $PORT

CMD pnpm run $MODE
