local-run:
	docker compose -f docker-compose-local.yaml up
local-stop:
	docker compose -f docker-compose-local.yaml down

deploy-run:
	docker compose -f docker-compose-deploy.yaml up
deploy-stop:
	docker compose -f docker-compose-deploy.yaml down
