run-local:
	docker compose -f docker-compose-local.yaml up
stop-local:
	docker compose -f docker-compose-local.yaml down

run-deploy:
	docker compose -f docker-compose-deploy.yaml up
stop-deploy:
	docker compose -f docker-compose-deploy.yaml down
