version: "3.8"
services:
  myapp:
    container_name: multitenancy-container
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        - PORT=${PORT}
        - MODE=${MODE}
    ports:
      - 8080:${PORT}
    volumes:
      - ./:/app
      - exclude:/app/node_modules/

volumes:
  exclude:
