version: "3.4"
services:
  myapp:
    container_name: multitenancy-container
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules/

volumes:
  exclude:
